# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: member.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='member.proto',
  package='',
  serialized_pb='\n\x0cmember.proto\"o\n\x06Member\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04nick\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\x12\x14\n\x0c\x61vatar_small\x18\x04 \x01(\t\x12\x12\n\navatar_mid\x18\x05 \x01(\t\x12\x12\n\navatar_big\x18\x06 \x01(\t\"m\n\x10Register_Request\x12\r\n\x05phone\x18\x01 \x02(\t\x12\x10\n\x08\x61uthcode\x18\x02 \x02(\x05\x12\x10\n\x08password\x18\x03 \x02(\t\x12\x18\n\x10\x63onfirm_password\x18\x04 \x02(\t\x12\x0c\n\x04nick\x18\x05 \x02(\t\"M\n\x11Register_Response\x12\x17\n\x06member\x18\x01 \x01(\x0b\x32\x07.Member\x12\x1f\n\nerror_code\x18\x02 \x02(\x0e\x32\x0b.Error_Code\"6\n\x13Phone_Login_Reqeust\x12\r\n\x05phone\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"P\n\x14Phone_Login_Response\x12\x17\n\x06member\x18\x01 \x01(\x0b\x32\x07.Member\x12\x1f\n\nerror_code\x18\x02 \x02(\x0e\x32\x0b.Error_Code\":\n\x17Verify_Authcode_Request\x12\r\n\x05phone\x18\x01 \x02(\t\x12\x10\n\x08\x61uthcode\x18\x02 \x02(\x05\";\n\x18Verify_Authcode_Response\x12\x1f\n\nerror_code\x18\x01 \x02(\x0e\x32\x0b.Error_Code\")\n\x18Request_Authcode_Request\x12\r\n\x05phone\x18\x01 \x02(\t\"N\n\x19Request_Authcode_Response\x12\x10\n\x08\x61uthcode\x18\x01 \x01(\x05\x12\x1f\n\nerror_code\x18\x02 \x02(\x0e\x32\x0b.Error_Code*l\n\x08Protocol\x12\x0e\n\nUNKNOW_CMD\x10\x00\x12\x11\n\x0bPHONE_LOGIN\x10\xb1\xdb\x06\x12\x0e\n\x08REGISTER\x10\xb2\xdb\x06\x12\x16\n\x10REQUEST_AUTHCODE\x10\xb3\xdb\x06\x12\x15\n\x0fVERIFY_AUTHCODE\x10\xb4\xdb\x06*\xe6\x01\n\nError_Code\x12\x0b\n\x07SUCCESS\x10\x00\x12\x1c\n\x16\x45RROR_INVALID_PASSWORD\x10\xb0\xdb\x06\x12\x1e\n\x18\x45RROR_PASSWORD_NOT_EQUAL\x10\xb1\xdb\x06\x12\x18\n\x12\x45RROR_MEMBER_EXIST\x10\xb2\xdb\x06\x12\x1c\n\x16\x45RROR_AUTHCODE_INVALID\x10\xb3\xdb\x06\x12\x19\n\x13\x45RROR_PHONE_INVALID\x10\xb4\xdb\x06\x12\x1c\n\x16\x45RROR_AUTHCODE_EXPIRED\x10\xb5\xdb\x06\x12\x1c\n\x16\x45RROR_MEMBER_NOT_FOUND\x10\xb6\xdb\x06')

_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOW_CMD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PHONE_LOGIN', index=1, number=110001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REGISTER', index=2, number=110002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUEST_AUTHCODE', index=3, number=110003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERIFY_AUTHCODE', index=4, number=110004,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=701,
  serialized_end=809,
)

Protocol = enum_type_wrapper.EnumTypeWrapper(_PROTOCOL)
_ERROR_CODE = _descriptor.EnumDescriptor(
  name='Error_Code',
  full_name='Error_Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_PASSWORD', index=1, number=110000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_PASSWORD_NOT_EQUAL', index=2, number=110001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_MEMBER_EXIST', index=3, number=110002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_AUTHCODE_INVALID', index=4, number=110003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_PHONE_INVALID', index=5, number=110004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_AUTHCODE_EXPIRED', index=6, number=110005,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_MEMBER_NOT_FOUND', index=7, number=110006,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=812,
  serialized_end=1042,
)

Error_Code = enum_type_wrapper.EnumTypeWrapper(_ERROR_CODE)
UNKNOW_CMD = 0
PHONE_LOGIN = 110001
REGISTER = 110002
REQUEST_AUTHCODE = 110003
VERIFY_AUTHCODE = 110004
SUCCESS = 0
ERROR_INVALID_PASSWORD = 110000
ERROR_PASSWORD_NOT_EQUAL = 110001
ERROR_MEMBER_EXIST = 110002
ERROR_AUTHCODE_INVALID = 110003
ERROR_PHONE_INVALID = 110004
ERROR_AUTHCODE_EXPIRED = 110005
ERROR_MEMBER_NOT_FOUND = 110006



_MEMBER = _descriptor.Descriptor(
  name='Member',
  full_name='Member',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Member.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nick', full_name='Member.nick', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phone', full_name='Member.phone', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar_small', full_name='Member.avatar_small', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar_mid', full_name='Member.avatar_mid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avatar_big', full_name='Member.avatar_big', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=127,
)


_REGISTER_REQUEST = _descriptor.Descriptor(
  name='Register_Request',
  full_name='Register_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='Register_Request.phone', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authcode', full_name='Register_Request.authcode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='Register_Request.password', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='confirm_password', full_name='Register_Request.confirm_password', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nick', full_name='Register_Request.nick', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=238,
)


_REGISTER_RESPONSE = _descriptor.Descriptor(
  name='Register_Response',
  full_name='Register_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='member', full_name='Register_Response.member', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Register_Response.error_code', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=240,
  serialized_end=317,
)


_PHONE_LOGIN_REQEUST = _descriptor.Descriptor(
  name='Phone_Login_Reqeust',
  full_name='Phone_Login_Reqeust',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='Phone_Login_Reqeust.phone', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='Phone_Login_Reqeust.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=319,
  serialized_end=373,
)


_PHONE_LOGIN_RESPONSE = _descriptor.Descriptor(
  name='Phone_Login_Response',
  full_name='Phone_Login_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='member', full_name='Phone_Login_Response.member', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Phone_Login_Response.error_code', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=375,
  serialized_end=455,
)


_VERIFY_AUTHCODE_REQUEST = _descriptor.Descriptor(
  name='Verify_Authcode_Request',
  full_name='Verify_Authcode_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='Verify_Authcode_Request.phone', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authcode', full_name='Verify_Authcode_Request.authcode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=457,
  serialized_end=515,
)


_VERIFY_AUTHCODE_RESPONSE = _descriptor.Descriptor(
  name='Verify_Authcode_Response',
  full_name='Verify_Authcode_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Verify_Authcode_Response.error_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=517,
  serialized_end=576,
)


_REQUEST_AUTHCODE_REQUEST = _descriptor.Descriptor(
  name='Request_Authcode_Request',
  full_name='Request_Authcode_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phone', full_name='Request_Authcode_Request.phone', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=578,
  serialized_end=619,
)


_REQUEST_AUTHCODE_RESPONSE = _descriptor.Descriptor(
  name='Request_Authcode_Response',
  full_name='Request_Authcode_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='authcode', full_name='Request_Authcode_Response.authcode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Request_Authcode_Response.error_code', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=621,
  serialized_end=699,
)

_REGISTER_RESPONSE.fields_by_name['member'].message_type = _MEMBER
_REGISTER_RESPONSE.fields_by_name['error_code'].enum_type = _ERROR_CODE
_PHONE_LOGIN_RESPONSE.fields_by_name['member'].message_type = _MEMBER
_PHONE_LOGIN_RESPONSE.fields_by_name['error_code'].enum_type = _ERROR_CODE
_VERIFY_AUTHCODE_RESPONSE.fields_by_name['error_code'].enum_type = _ERROR_CODE
_REQUEST_AUTHCODE_RESPONSE.fields_by_name['error_code'].enum_type = _ERROR_CODE
DESCRIPTOR.message_types_by_name['Member'] = _MEMBER
DESCRIPTOR.message_types_by_name['Register_Request'] = _REGISTER_REQUEST
DESCRIPTOR.message_types_by_name['Register_Response'] = _REGISTER_RESPONSE
DESCRIPTOR.message_types_by_name['Phone_Login_Reqeust'] = _PHONE_LOGIN_REQEUST
DESCRIPTOR.message_types_by_name['Phone_Login_Response'] = _PHONE_LOGIN_RESPONSE
DESCRIPTOR.message_types_by_name['Verify_Authcode_Request'] = _VERIFY_AUTHCODE_REQUEST
DESCRIPTOR.message_types_by_name['Verify_Authcode_Response'] = _VERIFY_AUTHCODE_RESPONSE
DESCRIPTOR.message_types_by_name['Request_Authcode_Request'] = _REQUEST_AUTHCODE_REQUEST
DESCRIPTOR.message_types_by_name['Request_Authcode_Response'] = _REQUEST_AUTHCODE_RESPONSE

class Member(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _MEMBER

  # @@protoc_insertion_point(class_scope:Member)

class Register_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTER_REQUEST

  # @@protoc_insertion_point(class_scope:Register_Request)

class Register_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTER_RESPONSE

  # @@protoc_insertion_point(class_scope:Register_Response)

class Phone_Login_Reqeust(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHONE_LOGIN_REQEUST

  # @@protoc_insertion_point(class_scope:Phone_Login_Reqeust)

class Phone_Login_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PHONE_LOGIN_RESPONSE

  # @@protoc_insertion_point(class_scope:Phone_Login_Response)

class Verify_Authcode_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERIFY_AUTHCODE_REQUEST

  # @@protoc_insertion_point(class_scope:Verify_Authcode_Request)

class Verify_Authcode_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VERIFY_AUTHCODE_RESPONSE

  # @@protoc_insertion_point(class_scope:Verify_Authcode_Response)

class Request_Authcode_Request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_AUTHCODE_REQUEST

  # @@protoc_insertion_point(class_scope:Request_Authcode_Request)

class Request_Authcode_Response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST_AUTHCODE_RESPONSE

  # @@protoc_insertion_point(class_scope:Request_Authcode_Response)


# @@protoc_insertion_point(module_scope)
