# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payment.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rpayment.proto\"a\n\x06Wechat\x12\r\n\x05\x61ppid\x18\x01 \x02(\t\x12\x10\n\x08noncestr\x18\x02 \x02(\t\x12\x10\n\x08packages\x18\x03 \x02(\t\x12\x11\n\tpartnerid\x18\x04 \x02(\t\x12\x11\n\ttimestamp\x18\x05 \x02(\x05\"\xfa\x01\n\x06\x41lipay\x12\x0c\n\x04\x62ody\x18\x01 \x02(\t\x12\x11\n\tseller_id\x18\x02 \x02(\t\x12\x11\n\ttotal_fee\x18\x03 \x02(\x02\x12\x10\n\x08services\x18\x04 \x02(\t\x12\x15\n\rinput_charset\x18\x05 \x02(\t\x12\x10\n\x08it_b_pay\x18\x06 \x02(\t\x12\x14\n\x0cout_trade_no\x18\x07 \x02(\t\x12\x14\n\x0cpayment_type\x18\x08 \x02(\t\x12\x12\n\nnotify_url\x18\t \x02(\t\x12\x11\n\tsign_type\x18\n \x02(\t\x12\x0f\n\x07partner\x18\x0b \x02(\t\x12\x0c\n\x04sign\x18\x0c \x02(\t\x12\x0f\n\x07subject\x18\r \x02(\t\"\"\n\x0eWechat_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\"V\n\x0fWechat_Response\x12\x1a\n\tparamters\x18\x01 \x01(\x0b\x32\x07.Wechat\x12\'\n\nerror_code\x18\x07 \x02(\x0e\x32\x13.Payment_Error_Code\"\"\n\x0e\x41lipay_Request\x12\x10\n\x08order_id\x18\x01 \x02(\t\"V\n\x0f\x41lipay_Response\x12\x1a\n\tparamters\x18\x01 \x01(\x0b\x32\x07.Alipay\x12\'\n\nerror_code\x18\x02 \x02(\x0e\x32\x13.Payment_Error_Code*>\n\x10Payment_Protocol\x12\x0e\n\nUNKNOW_CMD\x10\x00\x12\x0c\n\x06WECHAT\x10\xe0\xc5\x08\x12\x0c\n\x06\x41LIPAY\x10\xe1\xc5\x08*M\n\x12Payment_Error_Code\x12\x1b\n\x15\x45RROR_ORDER_NOT_FOUND\x10\xe0\xc5\x08\x12\x1a\n\x14\x45RROR_PREPAY_FAILURE\x10\xe1\xc5\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PAYMENT_PROTOCOL = _descriptor.EnumDescriptor(
  name='Payment_Protocol',
  full_name='Payment_Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOW_CMD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WECHAT', index=1, number=140000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALIPAY', index=2, number=140001,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=617,
  serialized_end=679,
)
_sym_db.RegisterEnumDescriptor(_PAYMENT_PROTOCOL)

Payment_Protocol = enum_type_wrapper.EnumTypeWrapper(_PAYMENT_PROTOCOL)
_PAYMENT_ERROR_CODE = _descriptor.EnumDescriptor(
  name='Payment_Error_Code',
  full_name='Payment_Error_Code',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR_ORDER_NOT_FOUND', index=0, number=140000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_PREPAY_FAILURE', index=1, number=140001,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=681,
  serialized_end=758,
)
_sym_db.RegisterEnumDescriptor(_PAYMENT_ERROR_CODE)

Payment_Error_Code = enum_type_wrapper.EnumTypeWrapper(_PAYMENT_ERROR_CODE)
UNKNOW_CMD = 0
WECHAT = 140000
ALIPAY = 140001
ERROR_ORDER_NOT_FOUND = 140000
ERROR_PREPAY_FAILURE = 140001



_WECHAT = _descriptor.Descriptor(
  name='Wechat',
  full_name='Wechat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='appid', full_name='Wechat.appid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='noncestr', full_name='Wechat.noncestr', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='packages', full_name='Wechat.packages', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partnerid', full_name='Wechat.partnerid', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Wechat.timestamp', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=114,
)


_ALIPAY = _descriptor.Descriptor(
  name='Alipay',
  full_name='Alipay',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='Alipay.body', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seller_id', full_name='Alipay.seller_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_fee', full_name='Alipay.total_fee', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='services', full_name='Alipay.services', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input_charset', full_name='Alipay.input_charset', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='it_b_pay', full_name='Alipay.it_b_pay', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_trade_no', full_name='Alipay.out_trade_no', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payment_type', full_name='Alipay.payment_type', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notify_url', full_name='Alipay.notify_url', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sign_type', full_name='Alipay.sign_type', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partner', full_name='Alipay.partner', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sign', full_name='Alipay.sign', index=11,
      number=12, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='subject', full_name='Alipay.subject', index=12,
      number=13, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=367,
)


_WECHAT_REQUEST = _descriptor.Descriptor(
  name='Wechat_Request',
  full_name='Wechat_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Wechat_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=403,
)


_WECHAT_RESPONSE = _descriptor.Descriptor(
  name='Wechat_Response',
  full_name='Wechat_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paramters', full_name='Wechat_Response.paramters', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Wechat_Response.error_code', index=1,
      number=7, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=140000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=491,
)


_ALIPAY_REQUEST = _descriptor.Descriptor(
  name='Alipay_Request',
  full_name='Alipay_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='order_id', full_name='Alipay_Request.order_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=527,
)


_ALIPAY_RESPONSE = _descriptor.Descriptor(
  name='Alipay_Response',
  full_name='Alipay_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paramters', full_name='Alipay_Response.paramters', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='Alipay_Response.error_code', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=140000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=615,
)

_WECHAT_RESPONSE.fields_by_name['paramters'].message_type = _WECHAT
_WECHAT_RESPONSE.fields_by_name['error_code'].enum_type = _PAYMENT_ERROR_CODE
_ALIPAY_RESPONSE.fields_by_name['paramters'].message_type = _ALIPAY
_ALIPAY_RESPONSE.fields_by_name['error_code'].enum_type = _PAYMENT_ERROR_CODE
DESCRIPTOR.message_types_by_name['Wechat'] = _WECHAT
DESCRIPTOR.message_types_by_name['Alipay'] = _ALIPAY
DESCRIPTOR.message_types_by_name['Wechat_Request'] = _WECHAT_REQUEST
DESCRIPTOR.message_types_by_name['Wechat_Response'] = _WECHAT_RESPONSE
DESCRIPTOR.message_types_by_name['Alipay_Request'] = _ALIPAY_REQUEST
DESCRIPTOR.message_types_by_name['Alipay_Response'] = _ALIPAY_RESPONSE
DESCRIPTOR.enum_types_by_name['Payment_Protocol'] = _PAYMENT_PROTOCOL
DESCRIPTOR.enum_types_by_name['Payment_Error_Code'] = _PAYMENT_ERROR_CODE

Wechat = _reflection.GeneratedProtocolMessageType('Wechat', (_message.Message,), dict(
  DESCRIPTOR = _WECHAT,
  __module__ = 'payment_pb2'
  # @@protoc_insertion_point(class_scope:Wechat)
  ))
_sym_db.RegisterMessage(Wechat)

Alipay = _reflection.GeneratedProtocolMessageType('Alipay', (_message.Message,), dict(
  DESCRIPTOR = _ALIPAY,
  __module__ = 'payment_pb2'
  # @@protoc_insertion_point(class_scope:Alipay)
  ))
_sym_db.RegisterMessage(Alipay)

Wechat_Request = _reflection.GeneratedProtocolMessageType('Wechat_Request', (_message.Message,), dict(
  DESCRIPTOR = _WECHAT_REQUEST,
  __module__ = 'payment_pb2'
  # @@protoc_insertion_point(class_scope:Wechat_Request)
  ))
_sym_db.RegisterMessage(Wechat_Request)

Wechat_Response = _reflection.GeneratedProtocolMessageType('Wechat_Response', (_message.Message,), dict(
  DESCRIPTOR = _WECHAT_RESPONSE,
  __module__ = 'payment_pb2'
  # @@protoc_insertion_point(class_scope:Wechat_Response)
  ))
_sym_db.RegisterMessage(Wechat_Response)

Alipay_Request = _reflection.GeneratedProtocolMessageType('Alipay_Request', (_message.Message,), dict(
  DESCRIPTOR = _ALIPAY_REQUEST,
  __module__ = 'payment_pb2'
  # @@protoc_insertion_point(class_scope:Alipay_Request)
  ))
_sym_db.RegisterMessage(Alipay_Request)

Alipay_Response = _reflection.GeneratedProtocolMessageType('Alipay_Response', (_message.Message,), dict(
  DESCRIPTOR = _ALIPAY_RESPONSE,
  __module__ = 'payment_pb2'
  # @@protoc_insertion_point(class_scope:Alipay_Response)
  ))
_sym_db.RegisterMessage(Alipay_Response)


# @@protoc_insertion_point(module_scope)
