#!/usr/bin/python 
# -*- coding: utf-8 -*- 

SERVER_HOST = "localhost"
SERVER_PORT = 8888

SOCKET_HEADER_LENGTH   = 20
SOCKET_RECEIVE_TIMEOUT = 12

AUTHCODE_MIN = 1000
AUTHCODE_MAX = 9999
AUTHCODE_EXPIRED_AFTER = 300
